/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChooseCategoryRouteImport } from './routes/choose-category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayingCategoryRouteImport } from './routes/playing.$category'

const ChooseCategoryRoute = ChooseCategoryRouteImport.update({
  id: '/choose-category',
  path: '/choose-category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayingCategoryRoute = PlayingCategoryRouteImport.update({
  id: '/playing/$category',
  path: '/playing/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-category': typeof ChooseCategoryRoute
  '/playing/$category': typeof PlayingCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-category': typeof ChooseCategoryRoute
  '/playing/$category': typeof PlayingCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-category': typeof ChooseCategoryRoute
  '/playing/$category': typeof PlayingCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/choose-category' | '/playing/$category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/choose-category' | '/playing/$category'
  id: '__root__' | '/' | '/choose-category' | '/playing/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseCategoryRoute: typeof ChooseCategoryRoute
  PlayingCategoryRoute: typeof PlayingCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/choose-category': {
      id: '/choose-category'
      path: '/choose-category'
      fullPath: '/choose-category'
      preLoaderRoute: typeof ChooseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playing/$category': {
      id: '/playing/$category'
      path: '/playing/$category'
      fullPath: '/playing/$category'
      preLoaderRoute: typeof PlayingCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseCategoryRoute: ChooseCategoryRoute,
  PlayingCategoryRoute: PlayingCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
