/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChooseRoomRouteImport } from './routes/choose-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaitingRoomIdRouteImport } from './routes/waiting.$roomId'
import { Route as PlayingRoomIdRouteImport } from './routes/playing.$roomId'
import { Route as PlayingCategoryRouteImport } from './routes/playing.$category'

const ChooseRoomRoute = ChooseRoomRouteImport.update({
  id: '/choose-room',
  path: '/choose-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoomIdRoute = WaitingRoomIdRouteImport.update({
  id: '/waiting/$roomId',
  path: '/waiting/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayingRoomIdRoute = PlayingRoomIdRouteImport.update({
  id: '/playing/$roomId',
  path: '/playing/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayingCategoryRoute = PlayingCategoryRouteImport.update({
  id: '/playing/$category',
  path: '/playing/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-room': typeof ChooseRoomRoute
  '/playing/$category': typeof PlayingCategoryRoute
  '/playing/$roomId': typeof PlayingRoomIdRoute
  '/waiting/$roomId': typeof WaitingRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-room': typeof ChooseRoomRoute
  '/playing/$category': typeof PlayingCategoryRoute
  '/playing/$roomId': typeof PlayingRoomIdRoute
  '/waiting/$roomId': typeof WaitingRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-room': typeof ChooseRoomRoute
  '/playing/$category': typeof PlayingCategoryRoute
  '/playing/$roomId': typeof PlayingRoomIdRoute
  '/waiting/$roomId': typeof WaitingRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-room'
    | '/playing/$category'
    | '/playing/$roomId'
    | '/waiting/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-room'
    | '/playing/$category'
    | '/playing/$roomId'
    | '/waiting/$roomId'
  id:
    | '__root__'
    | '/'
    | '/choose-room'
    | '/playing/$category'
    | '/playing/$roomId'
    | '/waiting/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseRoomRoute: typeof ChooseRoomRoute
  PlayingCategoryRoute: typeof PlayingCategoryRoute
  PlayingRoomIdRoute: typeof PlayingRoomIdRoute
  WaitingRoomIdRoute: typeof WaitingRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/choose-room': {
      id: '/choose-room'
      path: '/choose-room'
      fullPath: '/choose-room'
      preLoaderRoute: typeof ChooseRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting/$roomId': {
      id: '/waiting/$roomId'
      path: '/waiting/$roomId'
      fullPath: '/waiting/$roomId'
      preLoaderRoute: typeof WaitingRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playing/$roomId': {
      id: '/playing/$roomId'
      path: '/playing/$roomId'
      fullPath: '/playing/$roomId'
      preLoaderRoute: typeof PlayingRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playing/$category': {
      id: '/playing/$category'
      path: '/playing/$category'
      fullPath: '/playing/$category'
      preLoaderRoute: typeof PlayingCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseRoomRoute: ChooseRoomRoute,
  PlayingCategoryRoute: PlayingCategoryRoute,
  PlayingRoomIdRoute: PlayingRoomIdRoute,
  WaitingRoomIdRoute: WaitingRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
